// Across — starter word/clue bank.
//
// Hand-authored for this project rather than scraped from a published
// crossword corpus, to sidestep the copyright/licensing questions around
// redistributing someone else's clue text. It's intentionally modest in
// size (a few hundred entries) — enough to generate real small-to-medium
// puzzles across the categories the Search screen advertises, but you'll
// want to grow this over time (or swap in a larger licensed corpus) as
// players notice repeats. Difficulty: 1 = easy, 2 = medium, 3 = hard.
//
// `cat` values match the Search screen's category chips (lowercase):
// geography, movies, history, sports, science, food, kids, general.

export const WORD_BANK = [
  // ---- geography ----
  { w: "PARIS", c: "City of Light", cat: "geography", diff: 1 },
  { w: "PRAGUE", c: "Czech capital on the Vltava", cat: "geography", diff: 2 },
  { w: "BERLIN", c: "German capital", cat: "geography", diff: 1 },
  { w: "TOKYO", c: "World's most populous metro area", cat: "geography", diff: 1 },
  { w: "CAIRO", c: "Egyptian capital near the pyramids", cat: "geography", diff: 2 },
  { w: "ROME", c: "The Eternal City", cat: "geography", diff: 1 },
  { w: "MADRID", c: "Spanish capital", cat: "geography", diff: 2 },
  { w: "LONDON", c: "City on the Thames", cat: "geography", diff: 1 },
  { w: "OSLO", c: "Norwegian capital", cat: "geography", diff: 2 },
  { w: "LIMA", c: "Peruvian capital", cat: "geography", diff: 2 },
  { w: "SEOUL", c: "South Korean capital", cat: "geography", diff: 2 },
  { w: "DELHI", c: "Indian capital region", cat: "geography", diff: 2 },
  { w: "NILE", c: "Longest river in Africa", cat: "geography", diff: 1 },
  { w: "AMAZON", c: "River that carries the most water on Earth", cat: "geography", diff: 2 },
  { w: "ANDES", c: "Longest mountain range in the world", cat: "geography", diff: 2 },
  { w: "ALPS", c: "Mountain range crossing France, Switzerland, and Italy", cat: "geography", diff: 1 },
  { w: "SAHARA", c: "Largest hot desert", cat: "geography", diff: 2 },
  { w: "GOBI", c: "Desert spanning China and Mongolia", cat: "geography", diff: 3 },
  { w: "EVEREST", c: "Tallest mountain above sea level", cat: "geography", diff: 1 },
  { w: "PACIFIC", c: "Largest ocean", cat: "geography", diff: 1 },
  { w: "ATLANTIC", c: "Ocean between the Americas and Europe/Africa", cat: "geography", diff: 1 },
  { w: "ARCTIC", c: "Northernmost ocean", cat: "geography", diff: 2 },
  { w: "ITALY", c: "Boot-shaped country", cat: "geography", diff: 1 },
  { w: "JAPAN", c: "Land of the Rising Sun", cat: "geography", diff: 1 },
  { w: "CANADA", c: "Country with the most lakes", cat: "geography", diff: 1 },
  { w: "BRAZIL", c: "Largest country in South America", cat: "geography", diff: 1 },
  { w: "EGYPT", c: "Home of the Great Pyramids", cat: "geography", diff: 1 },
  { w: "KENYA", c: "East African country known for safaris", cat: "geography", diff: 2 },
  { w: "ICELAND", c: "Land of fire and ice", cat: "geography", diff: 2 },
  { w: "GREECE", c: "Birthplace of the Olympics", cat: "geography", diff: 1 },
  { w: "PERU", c: "Home of Machu Picchu", cat: "geography", diff: 2 },
  { w: "CHILE", c: "Long, thin South American country", cat: "geography", diff: 2 },
  { w: "VIENNA", c: "Austrian capital", cat: "geography", diff: 2 },
  { w: "DUBLIN", c: "Irish capital", cat: "geography", diff: 2 },
  { w: "ATHENS", c: "Greek capital", cat: "geography", diff: 2 },
  { w: "MOSCOW", c: "Russian capital", cat: "geography", diff: 1 },
  { w: "ISLAND", c: "Landmass surrounded by water", cat: "geography", diff: 1 },
  { w: "GLACIER", c: "Slow-moving river of ice", cat: "geography", diff: 2 },
  { w: "VOLCANO", c: "Mountain that can erupt", cat: "geography", diff: 1 },
  { w: "PENINSULA", c: "Land almost surrounded by water", cat: "geography", diff: 3 },
  { w: "EQUATOR", c: "Line at zero degrees latitude", cat: "geography", diff: 2 },

  // ---- movies ----
  { w: "JAWS", c: "1975 shark thriller", cat: "movies", diff: 1 },
  { w: "TITANIC", c: "1997 blockbuster with a doomed ship", cat: "movies", diff: 1 },
  { w: "AVATAR", c: "Highest-grossing film for years, set on Pandora", cat: "movies", diff: 1 },
  { w: "FROZEN", c: "Animated film with the song \"Let It Go\"", cat: "movies", diff: 1 },
  { w: "SHREK", c: "Animated ogre with layers, like an onion", cat: "movies", diff: 1 },
  { w: "ROCKY", c: "Underdog boxer film series", cat: "movies", diff: 2 },
  { w: "GREASE", c: "1978 musical set at Rydell High", cat: "movies", diff: 2 },
  { w: "MATRIX", c: "\"There is no spoon\" sci-fi film", cat: "movies", diff: 2 },
  { w: "INCEPTION", c: "Dream-within-a-dream heist film", cat: "movies", diff: 2 },
  { w: "GLADIATOR", c: "\"Are you not entertained?\" film", cat: "movies", diff: 2 },
  { w: "CASABLANCA", c: "\"Here's looking at you, kid\" classic", cat: "movies", diff: 3 },
  { w: "PSYCHO", c: "Hitchcock shower-scene thriller", cat: "movies", diff: 2 },
  { w: "ALIEN", c: "\"In space no one can hear you scream\"", cat: "movies", diff: 1 },
  { w: "ELF", c: "Will Ferrell holiday comedy", cat: "movies", diff: 1 },
  { w: "UP", c: "Pixar film that opens with balloons and a house", cat: "movies", diff: 1 },
  { w: "COCO", c: "Pixar film set on Día de los Muertos", cat: "movies", diff: 1 },
  { w: "MOANA", c: "Disney film about a wayfinder", cat: "movies", diff: 1 },
  { w: "MULAN", c: "Disney film about a warrior who takes her father's place", cat: "movies", diff: 2 },
  { w: "TANGLED", c: "Disney film featuring Rapunzel", cat: "movies", diff: 2 },
  { w: "BRAVE", c: "Pixar film with a Scottish archer princess", cat: "movies", diff: 2 },
  { w: "JOKER", c: "2019 Batman villain origin story", cat: "movies", diff: 2 },
  { w: "DUNE", c: "Sci-fi epic set on the desert planet Arrakis", cat: "movies", diff: 2 },
  { w: "GRAVITY", c: "2013 space survival thriller", cat: "movies", diff: 2 },
  { w: "GOODFELLAS", c: "Scorsese mob classic", cat: "movies", diff: 3 },
  { w: "AMADEUS", c: "Best Picture about Mozart's rival", cat: "movies", diff: 3 },
  { w: "ARGO", c: "Affleck-directed hostage-rescue film", cat: "movies", diff: 3 },
  { w: "OSCAR", c: "Golden statuette award", cat: "movies", diff: 1 },
  { w: "SEQUEL", c: "Follow-up film", cat: "movies", diff: 1 },
  { w: "DIRECTOR", c: "Person who calls \"action\"", cat: "movies", diff: 1 },
  { w: "CAMEO", c: "Brief celebrity appearance in a film", cat: "movies", diff: 2 },
  { w: "TRAILER", c: "Preview shown before a movie", cat: "movies", diff: 1 },
  { w: "SCRIPT", c: "A movie's written dialogue and directions", cat: "movies", diff: 1 },
  { w: "STUNT", c: "Dangerous on-screen feat", cat: "movies", diff: 1 },
  { w: "STUDIO", c: "Where a movie is produced", cat: "movies", diff: 1 },
  { w: "VILLAIN", c: "The bad guy of the story", cat: "movies", diff: 1 },

  // ---- history ----
  { w: "LINCOLN", c: "16th U.S. president", cat: "history", diff: 1 },
  { w: "WASHINGTON", c: "First U.S. president", cat: "history", diff: 1 },
  { w: "NAPOLEON", c: "French emperor exiled to Elba", cat: "history", diff: 2 },
  { w: "CLEOPATRA", c: "Last active pharaoh of Egypt", cat: "history", diff: 2 },
  { w: "CAESAR", c: "Roman dictator stabbed on the Ides of March", cat: "history", diff: 2 },
  { w: "GANDHI", c: "Leader of India's independence movement", cat: "history", diff: 2 },
  { w: "CHURCHILL", c: "WWII British prime minister", cat: "history", diff: 2 },
  { w: "COLUMBUS", c: "Explorer who sailed in 1492", cat: "history", diff: 1 },
  { w: "REVOLUTION", c: "Sudden, sweeping political change", cat: "history", diff: 2 },
  { w: "EMPIRE", c: "A far-reaching political dominion", cat: "history", diff: 1 },
  { w: "TREATY", c: "Formal agreement between nations", cat: "history", diff: 2 },
  { w: "COLONY", c: "Territory under another country's control", cat: "history", diff: 2 },
  { w: "PHARAOH", c: "Ancient Egyptian ruler", cat: "history", diff: 2 },
  { w: "KNIGHT", c: "Medieval mounted warrior", cat: "history", diff: 1 },
  { w: "CASTLE", c: "Fortified medieval residence", cat: "history", diff: 1 },
  { w: "VIKING", c: "Norse seafaring raider", cat: "history", diff: 1 },
  { w: "PYRAMID", c: "Ancient Egyptian tomb structure", cat: "history", diff: 1 },
  { w: "RENAISSANCE", c: "European cultural rebirth after the Middle Ages", cat: "history", diff: 3 },
  { w: "ARMISTICE", c: "Agreement to stop fighting", cat: "history", diff: 3 },
  { w: "DYNASTY", c: "Line of rulers from one family", cat: "history", diff: 2 },
  { w: "ARTIFACT", c: "Object of historical interest", cat: "history", diff: 2 },
  { w: "MONARCH", c: "A king or queen", cat: "history", diff: 2 },
  { w: "SIEGE", c: "Prolonged military blockade of a place", cat: "history", diff: 2 },

  // ---- sports ----
  { w: "SOCCER", c: "Sport called \"football\" almost everywhere else", cat: "sports", diff: 1 },
  { w: "TENNIS", c: "Sport played with a racket and net", cat: "sports", diff: 1 },
  { w: "HOCKEY", c: "Sport played on ice with a puck", cat: "sports", diff: 1 },
  { w: "GOLF", c: "Sport played with clubs and a small ball", cat: "sports", diff: 1 },
  { w: "RUGBY", c: "Sport with an oval ball and no forward passes", cat: "sports", diff: 2 },
  { w: "CRICKET", c: "Bat-and-ball sport big in England and India", cat: "sports", diff: 2 },
  { w: "BOXING", c: "Sport fought in a ring with gloves", cat: "sports", diff: 1 },
  { w: "SWIMMING", c: "Pool sport measured in laps", cat: "sports", diff: 1 },
  { w: "MARATHON", c: "26.2-mile race", cat: "sports", diff: 2 },
  { w: "OLYMPICS", c: "Global games held every four years", cat: "sports", diff: 1 },
  { w: "REFEREE", c: "Official who enforces the rules of a game", cat: "sports", diff: 2 },
  { w: "STADIUM", c: "Large venue for sporting events", cat: "sports", diff: 1 },
  { w: "TROPHY", c: "Prize for winning a competition", cat: "sports", diff: 1 },
  { w: "COACH", c: "Person who trains a team", cat: "sports", diff: 1 },
  { w: "GOALIE", c: "Player who guards the net", cat: "sports", diff: 1 },
  { w: "SERVE", c: "Opening shot in tennis or volleyball", cat: "sports", diff: 1 },
  { w: "DRIBBLE", c: "Bounce a ball while moving, in basketball", cat: "sports", diff: 1 },
  { w: "OFFSIDE", c: "Soccer rule about being too far forward", cat: "sports", diff: 3 },
  { w: "SPRINT", c: "Short, fast race", cat: "sports", diff: 1 },
  { w: "TACKLE", c: "Bring down an opponent with the ball", cat: "sports", diff: 1 },
  { w: "PUCK", c: "Disc used in ice hockey", cat: "sports", diff: 1 },
  { w: "PEDAL", c: "What a cyclist pushes to go", cat: "sports", diff: 1 },
  { w: "RACKET", c: "Tennis or badminton equipment", cat: "sports", diff: 1 },
  { w: "MEDAL", c: "What Olympic winners take home", cat: "sports", diff: 1 },
  { w: "ARENA", c: "Enclosed venue for sports or events", cat: "sports", diff: 1 },

  // ---- science ----
  { w: "GRAVITY", c: "Force that keeps you on the ground", cat: "science", diff: 1 },
  { w: "ATOM", c: "Smallest unit of an element", cat: "science", diff: 1 },
  { w: "OXYGEN", c: "Element you breathe in to live", cat: "science", diff: 1 },
  { w: "PLANET", c: "Earth, for instance", cat: "science", diff: 1 },
  { w: "GALAXY", c: "Massive collection of stars, like the Milky Way", cat: "science", diff: 1 },
  { w: "COMET", c: "Icy body that grows a tail near the sun", cat: "science", diff: 2 },
  { w: "NEURON", c: "Brain cell that transmits signals", cat: "science", diff: 2 },
  { w: "GENOME", c: "Complete set of an organism's DNA", cat: "science", diff: 3 },
  { w: "ENZYME", c: "Protein that speeds up a reaction", cat: "science", diff: 3 },
  { w: "VACCINE", c: "Shot that trains your immune system", cat: "science", diff: 2 },
  { w: "ECLIPSE", c: "Event where one body blocks another's light", cat: "science", diff: 2 },
  { w: "ORBIT", c: "Path a planet takes around the sun", cat: "science", diff: 1 },
  { w: "MOLECULE", c: "Two or more atoms bonded together", cat: "science", diff: 2 },
  { w: "GRAVITON", c: "Hypothetical particle carrying gravity", cat: "science", diff: 3 },
  { w: "PHOTON", c: "Particle of light", cat: "science", diff: 2 },
  { w: "MAGNET", c: "Object that attracts iron", cat: "science", diff: 1 },
  { w: "VOLTAGE", c: "Electrical potential difference", cat: "science", diff: 2 },
  { w: "BACTERIA", c: "Single-celled microorganisms", cat: "science", diff: 2 },
  { w: "FOSSIL", c: "Preserved remains of an ancient organism", cat: "science", diff: 1 },
  { w: "HABITAT", c: "An animal's natural home environment", cat: "science", diff: 1 },
  { w: "MAMMAL", c: "Warm-blooded animal that nurses its young", cat: "science", diff: 1 },
  { w: "REPTILE", c: "Cold-blooded, scaly animal like a lizard", cat: "science", diff: 1 },
  { w: "OTTER", c: "Playful river mammal", cat: "science", diff: 1 },
  { w: "SONAR", c: "Sound-based system, like a submarine's \"ears\"", cat: "science", diff: 2 },
  { w: "TELESCOPE", c: "Instrument for viewing distant stars", cat: "science", diff: 2 },
  { w: "MICROSCOPE", c: "Instrument for viewing tiny things", cat: "science", diff: 2 },

  // ---- food ----
  { w: "PIZZA", c: "Dish topped with cheese and sauce on dough", cat: "food", diff: 1 },
  { w: "SUSHI", c: "Japanese dish often featuring raw fish", cat: "food", diff: 1 },
  { w: "TACO", c: "Folded tortilla dish", cat: "food", diff: 1 },
  { w: "PASTA", c: "Italian noodle dish", cat: "food", diff: 1 },
  { w: "BURGER", c: "Sandwich with a beef patty", cat: "food", diff: 1 },
  { w: "WAFFLE", c: "Griddled breakfast dish with a grid pattern", cat: "food", diff: 1 },
  { w: "PANCAKE", c: "Flat, griddled breakfast dish", cat: "food", diff: 1 },
  { w: "OMELET", c: "Folded egg dish", cat: "food", diff: 2 },
  { w: "RISOTTO", c: "Creamy Italian rice dish", cat: "food", diff: 3 },
  { w: "CURRY", c: "Spiced dish common in South Asian cuisine", cat: "food", diff: 1 },
  { w: "RAMEN", c: "Japanese noodle soup", cat: "food", diff: 1 },
  { w: "DUMPLING", c: "Dough wrapped around a filling", cat: "food", diff: 2 },
  { w: "PRETZEL", c: "Twisted, salted snack", cat: "food", diff: 2 },
  { w: "BAGEL", c: "Boiled-then-baked ring-shaped bread", cat: "food", diff: 1 },
  { w: "CROISSANT", c: "Flaky, crescent-shaped French pastry", cat: "food", diff: 3 },
  { w: "AVOCADO", c: "Green fruit used in guacamole", cat: "food", diff: 1 },
  { w: "MANGO", c: "Sweet tropical stone fruit", cat: "food", diff: 1 },
  { w: "COCONUT", c: "Tropical fruit with a hard shell and milk inside", cat: "food", diff: 1 },
  { w: "GINGER", c: "Spicy root used in cooking and tea", cat: "food", diff: 2 },
  { w: "CINNAMON", c: "Warm spice from tree bark", cat: "food", diff: 2 },
  { w: "VANILLA", c: "Most common ice cream flavor", cat: "food", diff: 1 },
  { w: "CARAMEL", c: "Cooked-sugar candy or sauce", cat: "food", diff: 2 },
  { w: "PRETZELS", c: "Salty, twisted snacks eaten by the bag", cat: "food", diff: 2 },
  { w: "OMELETTE", c: "British spelling of a folded egg dish", cat: "food", diff: 2 },
  { w: "SPATULA", c: "Kitchen tool for flipping food", cat: "food", diff: 2 },
  { w: "SKILLET", c: "Frying pan", cat: "food", diff: 1 },
  { w: "RECIPE", c: "Instructions for cooking a dish", cat: "food", diff: 1 },
  { w: "SIMMER", c: "Cook gently just below boiling", cat: "food", diff: 2 },

  // ---- kids ----
  { w: "PUPPY", c: "Baby dog", cat: "kids", diff: 1 },
  { w: "KITTEN", c: "Baby cat", cat: "kids", diff: 1 },
  { w: "RAINBOW", c: "Colorful arc after rain", cat: "kids", diff: 1 },
  { w: "CRAYON", c: "Waxy coloring stick", cat: "kids", diff: 1 },
  { w: "BALLOON", c: "Inflatable party decoration", cat: "kids", diff: 1 },
  { w: "TEDDY", c: "Stuffed bear, for short", cat: "kids", diff: 1 },
  { w: "SWING", c: "Playground seat that goes back and forth", cat: "kids", diff: 1 },
  { w: "SLIDE", c: "Playground chute you go down", cat: "kids", diff: 1 },
  { w: "BUBBLE", c: "Soapy sphere that pops", cat: "kids", diff: 1 },
  { w: "COOKIE", c: "Sweet baked treat, often with chips in it", cat: "kids", diff: 1 },
  { w: "UNICORN", c: "Mythical horse with a horn", cat: "kids", diff: 1 },
  { w: "DRAGON", c: "Fire-breathing mythical creature", cat: "kids", diff: 1 },
  { w: "PIRATE", c: "Sea robber who says \"arr\"", cat: "kids", diff: 1 },
  { w: "ROBOT", c: "Mechanical, programmable helper", cat: "kids", diff: 1 },
  { w: "CASTLE", c: "Where a fairy-tale king or queen lives", cat: "kids", diff: 1 },
  { w: "WIZARD", c: "Spellcasting magic-user", cat: "kids", diff: 1 },
  { w: "SNOWMAN", c: "Figure built from three snowballs", cat: "kids", diff: 1 },
  { w: "TROPHY", c: "What you win first place with", cat: "kids", diff: 1 },
  { w: "SUPERHERO", c: "Caped crime-fighter", cat: "kids", diff: 2 },
  { w: "MERMAID", c: "Half-human, half-fish sea creature", cat: "kids", diff: 1 },
  { w: "GIGGLE", c: "Small, happy laugh", cat: "kids", diff: 1 },
  { w: "SPARKLE", c: "Small flash of light, like glitter", cat: "kids", diff: 1 },
  { w: "PUZZLE", c: "Game you piece together, like this one", cat: "kids", diff: 1 },
  { w: "SANDBOX", c: "Playground pit filled for digging", cat: "kids", diff: 1 },

  // ---- general (short connector words, help intersections across all sizes) ----
  { w: "ERASE", c: "Undo, as pencil marks", cat: "general", diff: 1 },
  { w: "OCEAN", c: "Vast body of salt water", cat: "general", diff: 1 },
  { w: "RIVER", c: "Flowing body of fresh water", cat: "general", diff: 1 },
  { w: "CLOUD", c: "Fluffy shape in the sky", cat: "general", diff: 1 },
  { w: "STORM", c: "Weather event with wind and rain", cat: "general", diff: 1 },
  { w: "LIGHT", c: "Opposite of dark", cat: "general", diff: 1 },
  { w: "MUSIC", c: "Organized sound, art form", cat: "general", diff: 1 },
  { w: "DANCE", c: "Rhythmic movement to music", cat: "general", diff: 1 },
  { w: "SMILE", c: "Happy facial expression", cat: "general", diff: 1 },
  { w: "DREAM", c: "What you experience while asleep", cat: "general", diff: 1 },
  { w: "TRAIN", c: "Vehicle that runs on rails", cat: "general", diff: 1 },
  { w: "PLANE", c: "Vehicle that flies", cat: "general", diff: 1 },
  { w: "BOAT", c: "Small watercraft", cat: "general", diff: 1 },
  { w: "ROAD", c: "Paved path for vehicles", cat: "general", diff: 1 },
  { w: "STAR", c: "Twinkling point of light at night", cat: "general", diff: 1 },
  { w: "MOON", c: "Earth's only natural satellite", cat: "general", diff: 1 },
  { w: "TREE", c: "Tall plant with a trunk", cat: "general", diff: 1 },
  { w: "LEAF", c: "Part of a tree that falls in autumn", cat: "general", diff: 1 },
  { w: "STONE", c: "Small rock", cat: "general", diff: 1 },
  { w: "GLASS", c: "Transparent material, or a drinking vessel", cat: "general", diff: 1 },
  { w: "PAPER", c: "What books and letters are printed on", cat: "general", diff: 1 },
  { w: "CHAIR", c: "Piece of furniture you sit on", cat: "general", diff: 1 },
  { w: "TABLE", c: "Flat furniture surface", cat: "general", diff: 1 },
  { w: "CLOCK", c: "Device that tells time", cat: "general", diff: 1 },
  { w: "MIRROR", c: "Reflective glass surface", cat: "general", diff: 1 },
  { w: "WINDOW", c: "Glass opening in a wall", cat: "general", diff: 1 },
  { w: "GARDEN", c: "Plot for growing plants", cat: "general", diff: 1 },
  { w: "FOREST", c: "Large area covered in trees", cat: "general", diff: 1 },
  { w: "DESERT", c: "Dry, sandy region", cat: "general", diff: 1 },
  { w: "ISLAND", c: "Body of land surrounded by water", cat: "general", diff: 1 },
  { w: "BRIDGE", c: "Structure crossing a river or gap", cat: "general", diff: 1 },
  { w: "TUNNEL", c: "Underground passage", cat: "general", diff: 1 },
  { w: "ENGINE", c: "Machine that converts fuel to motion", cat: "general", diff: 1 },
  { w: "ROCKET", c: "Vehicle that launches into space", cat: "general", diff: 1 },
  { w: "CAMERA", c: "Device that captures photos", cat: "general", diff: 1 },
  { w: "LETTER", c: "Written message, or a character like A", cat: "general", diff: 1 },
  { w: "NUMBER", c: "Mathematical value like 7", cat: "general", diff: 1 },
  { w: "COLOR", c: "Red, blue, or green, e.g.", cat: "general", diff: 1 },
  { w: "SHAPE", c: "Circle or square, e.g.", cat: "general", diff: 1 },
  { w: "ANSWER", c: "Response to a question", cat: "general", diff: 1 },
  { w: "SECRET", c: "Something kept hidden", cat: "general", diff: 1 },
  { w: "FRIEND", c: "Person you're close with", cat: "general", diff: 1 },
  { w: "FAMILY", c: "Parents, siblings, and relatives", cat: "general", diff: 1 },
  { w: "TRAVEL", c: "Go on a trip", cat: "general", diff: 1 },
  { w: "JOURNEY", c: "Long trip", cat: "general", diff: 1 },
  { w: "WINTER", c: "Coldest season", cat: "general", diff: 1 },
  { w: "SUMMER", c: "Warmest season", cat: "general", diff: 1 },
  { w: "AUTUMN", c: "Season also called fall", cat: "general", diff: 1 },
  { w: "SPRING", c: "Season of blooming flowers", cat: "general", diff: 1 },
  { w: "MORNING", c: "Start of the day", cat: "general", diff: 1 },
  { w: "EVENING", c: "End of the day", cat: "general", diff: 1 },
  { w: "SILENCE", c: "Complete quiet", cat: "general", diff: 2 },
  { w: "WHISPER", c: "Very quiet speech", cat: "general", diff: 1 },
  { w: "THUNDER", c: "Loud sound after lightning", cat: "general", diff: 1 },
  { w: "LIGHTNING", c: "Electric flash during a storm", cat: "general", diff: 1 },

  // ---- short fill words (3-4 letters, help intersections across all categories) ----
  { w: "SUN", c: "Star at the center of our solar system", cat: "general", diff: 1 },
  { w: "SEA", c: "Body of salt water, smaller than an ocean", cat: "general", diff: 1 },
  { w: "SKY", c: "What clouds float in", cat: "general", diff: 1 },
  { w: "ICE", c: "Frozen water", cat: "general", diff: 1 },
  { w: "AIR", c: "What we breathe", cat: "general", diff: 1 },
  { w: "MAP", c: "Guide for finding your way", cat: "general", diff: 1 },
  { w: "KEY", c: "Opens a lock", cat: "general", diff: 1 },
  { w: "BOX", c: "Square container", cat: "general", diff: 1 },
  { w: "CUP", c: "Small drinking vessel", cat: "general", diff: 1 },
  { w: "PEN", c: "Writing tool with ink", cat: "general", diff: 1 },
  { w: "HAT", c: "Head covering", cat: "general", diff: 1 },
  { w: "BAT", c: "Flying mammal, or baseball equipment", cat: "general", diff: 1 },
  { w: "OWL", c: "Nocturnal bird known for wisdom", cat: "general", diff: 1 },
  { w: "FOX", c: "Sly, red-furred animal", cat: "general", diff: 1 },
  { w: "BEE", c: "Buzzing pollinator", cat: "general", diff: 1 },
  { w: "ANT", c: "Tiny colony-building insect", cat: "general", diff: 1 },
  { w: "COW", c: "Farm animal that moos", cat: "general", diff: 1 },
  { w: "PIG", c: "Farm animal that oinks", cat: "general", diff: 1 },
  { w: "HEN", c: "Female chicken", cat: "general", diff: 1 },
  { w: "EGG", c: "What a hen lays", cat: "general", diff: 1 },
  { w: "ICE", c: "What forms on a pond in winter", cat: "general", diff: 1 },
  { w: "GEM", c: "Precious stone", cat: "general", diff: 1 },
  { w: "MAP", c: "Chart used for navigation", cat: "general", diff: 1 },
  { w: "LAKE", c: "Inland body of water", cat: "general", diff: 1 },
  { w: "PEAK", c: "Mountain's highest point", cat: "general", diff: 1 },
  { w: "COVE", c: "Small, sheltered bay", cat: "general", diff: 2 },
  { w: "REEF", c: "Coral-built underwater ridge", cat: "general", diff: 2 },
  { w: "DUNE", c: "Sand hill shaped by wind", cat: "general", diff: 2 },
  { w: "CAVE", c: "Underground hollow", cat: "general", diff: 1 },
  { w: "MIST", c: "Light fog", cat: "general", diff: 1 },
  { w: "GLOW", c: "Soft, steady light", cat: "general", diff: 1 },
  { w: "WAVE", c: "Ocean swell, or a hand gesture hello", cat: "general", diff: 1 },
  { w: "TIDE", c: "Rise and fall of the sea", cat: "general", diff: 2 },
  { w: "SAND", c: "What beaches are made of", cat: "general", diff: 1 },
  { w: "SNOW", c: "Frozen precipitation", cat: "general", diff: 1 },
  { w: "RAIN", c: "Falling water from clouds", cat: "general", diff: 1 },
  { w: "WIND", c: "Moving air", cat: "general", diff: 1 },
  { w: "LEAP", c: "Big jump", cat: "general", diff: 1 },
  { w: "RACE", c: "Speed competition", cat: "general", diff: 1 },
  { w: "GOAL", c: "Objective, or a score in soccer", cat: "general", diff: 1 },
  { w: "TEAM", c: "Group working together", cat: "general", diff: 1 },
  { w: "GAME", c: "Activity played for fun or competition", cat: "general", diff: 1 },
  { w: "PLAY", c: "What you do with a game or a toy", cat: "general", diff: 1 },
  { w: "WORK", c: "Job or effort", cat: "general", diff: 1 },
  { w: "REST", c: "Take a break", cat: "general", diff: 1 },
  { w: "WISH", c: "What you make on a birthday candle", cat: "general", diff: 1 },
  { w: "HOPE", c: "Optimistic feeling", cat: "general", diff: 1 },
  { w: "LOVE", c: "Deep affection", cat: "general", diff: 1 },
  { w: "JOKE", c: "Something told to get a laugh", cat: "general", diff: 1 },
  { w: "SONG", c: "Musical piece with lyrics", cat: "general", diff: 1 },
  { w: "TUNE", c: "Melody", cat: "general", diff: 1 },
  { w: "BEAT", c: "Rhythmic pulse in music", cat: "general", diff: 1 },
  { w: "NOTE", c: "Single musical sound, or a short written message", cat: "general", diff: 1 },

  // ---- geography (batch 2) ----
  { w: "AMSTERDAM", c: "Dutch capital known for its canals", cat: "geography", diff: 2 },
  { w: "LISBON", c: "Portuguese capital", cat: "geography", diff: 2 },
  { w: "HELSINKI", c: "Finnish capital", cat: "geography", diff: 3 },
  { w: "BANGKOK", c: "Thai capital", cat: "geography", diff: 2 },
  { w: "NAIROBI", c: "Kenyan capital", cat: "geography", diff: 3 },
  { w: "TORONTO", c: "Canada's most populous city", cat: "geography", diff: 2 },
  { w: "SYDNEY", c: "Australian harbor city with a famous opera house", cat: "geography", diff: 1 },
  { w: "VENICE", c: "Italian city built on canals", cat: "geography", diff: 1 },
  { w: "GENEVA", c: "Swiss city on a lake of the same name", cat: "geography", diff: 2 },
  { w: "ZURICH", c: "Switzerland's largest city", cat: "geography", diff: 3 },
  { w: "MEKONG", c: "River flowing through Southeast Asia", cat: "geography", diff: 3 },
  { w: "DANUBE", c: "River flowing through Vienna and Budapest", cat: "geography", diff: 3 },
  { w: "THAMES", c: "River flowing through London", cat: "geography", diff: 2 },
  { w: "URAL", c: "Mountain range dividing Europe and Asia", cat: "geography", diff: 3 },
  { w: "ATLAS", c: "Mountain range in northwest Africa", cat: "geography", diff: 3 },
  { w: "TUNDRA", c: "Cold, treeless biome near the poles", cat: "geography", diff: 2 },
  { w: "SAVANNA", c: "Grassy plain dotted with scattered trees", cat: "geography", diff: 2 },
  { w: "RAINFOREST", c: "Dense, wet, biodiverse forest biome", cat: "geography", diff: 2 },
  { w: "FJORD", c: "Narrow inlet carved by a glacier", cat: "geography", diff: 3 },
  { w: "ARCHIPELAGO", c: "A cluster of islands", cat: "geography", diff: 3 },
  { w: "CONTINENT", c: "Landmass like Africa or Asia", cat: "geography", diff: 1 },
  { w: "HEMISPHERE", c: "Half of the globe, north or south", cat: "geography", diff: 2 },
  { w: "LATITUDE", c: "Distance north or south of the equator", cat: "geography", diff: 3 },
  { w: "LONGITUDE", c: "Distance east or west of the prime meridian", cat: "geography", diff: 3 },
  { w: "BORDER", c: "Line dividing two countries", cat: "geography", diff: 1 },
  { w: "CAPITAL", c: "A country's seat of government", cat: "geography", diff: 1 },
  { w: "HARBOR", c: "Sheltered body of water for ships", cat: "geography", diff: 1 },
  { w: "PLATEAU", c: "Elevated, mostly flat area of land", cat: "geography", diff: 2 },
  { w: "CANYON", c: "Deep gorge carved by a river", cat: "geography", diff: 1 },
  { w: "DELTA", c: "Fan-shaped land where a river meets the sea", cat: "geography", diff: 2 },
  { w: "STRAIT", c: "Narrow waterway connecting two seas", cat: "geography", diff: 3 },
  { w: "GLOBE", c: "Spherical model of the Earth", cat: "geography", diff: 1 },
  { w: "COMPASS", c: "Tool that always points north", cat: "geography", diff: 1 },

  // ---- movies (batch 2) ----
  { w: "PIXAR", c: "Animation studio behind Toy Story", cat: "movies", diff: 1 },
  { w: "MARVEL", c: "Studio behind the Avengers franchise", cat: "movies", diff: 1 },
  { w: "SEQUELS", c: "Second, third, and later installments", cat: "movies", diff: 1 },
  { w: "REMAKE", c: "New version of an older film", cat: "movies", diff: 2 },
  { w: "PREMIERE", c: "A film's first public showing", cat: "movies", diff: 2 },
  { w: "BLOCKBUSTER", c: "A hugely successful hit film", cat: "movies", diff: 2 },
  { w: "SOUNDTRACK", c: "A film's musical accompaniment album", cat: "movies", diff: 2 },
  { w: "SUBTITLE", c: "On-screen translation of dialogue", cat: "movies", diff: 2 },
  { w: "SCREENPLAY", c: "The written blueprint for a film", cat: "movies", diff: 2 },
  { w: "PRODUCER", c: "Person who finances and oversees a film", cat: "movies", diff: 2 },
  { w: "ANIMATOR", c: "Artist who brings drawn characters to life", cat: "movies", diff: 2 },
  { w: "CASTING", c: "Choosing actors for roles", cat: "movies", diff: 2 },
  { w: "REHEARSAL", c: "Practice run before filming or a live show", cat: "movies", diff: 2 },
  { w: "CLIMAX", c: "The most intense point of a story", cat: "movies", diff: 2 },
  { w: "PLOT", c: "The storyline of a film", cat: "movies", diff: 1 },
  { w: "GENRE", c: "Category like horror, comedy, or drama", cat: "movies", diff: 1 },
  { w: "COMEDY", c: "Genre meant to make you laugh", cat: "movies", diff: 1 },
  { w: "THRILLER", c: "Genre built on suspense", cat: "movies", diff: 1 },
  { w: "WESTERN", c: "Genre set in the American frontier", cat: "movies", diff: 2 },
  { w: "MUSICAL", c: "Genre where characters break into song", cat: "movies", diff: 1 },
  { w: "DOCUMENTARY", c: "Non-fiction film genre", cat: "movies", diff: 2 },
  { w: "ANIMATION", c: "Genre built frame by frame rather than filmed live", cat: "movies", diff: 1 },
  { w: "POPCORN", c: "Classic movie-theater snack", cat: "movies", diff: 1 },
  { w: "MATINEE", c: "An afternoon showing of a film", cat: "movies", diff: 3 },
  { w: "MARQUEE", c: "The sign out front announcing what's playing", cat: "movies", diff: 3 },

  // ---- history (batch 2) ----
  { w: "ARMOR", c: "Protective gear worn by knights", cat: "history", diff: 1 },
  { w: "SWORD", c: "Bladed weapon carried by knights", cat: "history", diff: 1 },
  { w: "SHIELD", c: "Defensive gear held in one hand", cat: "history", diff: 1 },
  { w: "THRONE", c: "The seat a monarch rules from", cat: "history", diff: 1 },
  { w: "CROWN", c: "Headpiece worn by a king or queen", cat: "history", diff: 1 },
  { w: "PALACE", c: "Grand residence of a royal family", cat: "history", diff: 1 },
  { w: "FORTRESS", c: "A heavily defended stronghold", cat: "history", diff: 2 },
  { w: "RUINS", c: "What's left of an ancient structure", cat: "history", diff: 1 },
  { w: "SCROLL", c: "Rolled-up ancient document", cat: "history", diff: 2 },
  { w: "TABLET", c: "Ancient inscribed stone or clay slab", cat: "history", diff: 2 },
  { w: "EXPEDITION", c: "A long journey undertaken for exploration", cat: "history", diff: 2 },
  { w: "SETTLER", c: "Someone who establishes a new colony", cat: "history", diff: 2 },
  { w: "PIONEER", c: "One of the first to explore or settle a region", cat: "history", diff: 1 },
  { w: "MERCHANT", c: "Trader who buys and sells goods", cat: "history", diff: 2 },
  { w: "CARAVAN", c: "A group of traders traveling together", cat: "history", diff: 2 },
  { w: "COMPASS", c: "Navigation tool that changed exploration", cat: "history", diff: 1 },
  { w: "GALLEON", c: "Large sailing ship used for trade and war", cat: "history", diff: 3 },
  { w: "MUSKET", c: "Early long-barreled firearm", cat: "history", diff: 3 },
  { w: "REBELLION", c: "An organized uprising against authority", cat: "history", diff: 2 },
  { w: "INDEPENDENCE", c: "Freedom from outside control", cat: "history", diff: 2 },
  { w: "CONSTITUTION", c: "A nation's foundational set of laws", cat: "history", diff: 2 },
  { w: "SENATE", c: "A governing legislative body", cat: "history", diff: 2 },
  { w: "DECREE", c: "An official order with the force of law", cat: "history", diff: 3 },

  // ---- sports (batch 2) ----
  { w: "VOLLEYBALL", c: "Sport played over a net without a bounce", cat: "sports", diff: 1 },
  { w: "BADMINTON", c: "Racket sport played with a shuttlecock", cat: "sports", diff: 2 },
  { w: "LACROSSE", c: "Sport played with a netted stick", cat: "sports", diff: 3 },
  { w: "WRESTLING", c: "Sport of grappling to pin an opponent", cat: "sports", diff: 1 },
  { w: "FENCING", c: "Sport of sword dueling for points", cat: "sports", diff: 2 },
  { w: "ARCHERY", c: "Sport of shooting a bow at a target", cat: "sports", diff: 1 },
  { w: "ROWING", c: "Sport of racing boats with oars", cat: "sports", diff: 2 },
  { w: "SURFING", c: "Sport of riding ocean waves on a board", cat: "sports", diff: 1 },
  { w: "SKIING", c: "Winter sport of gliding down snow on two boards", cat: "sports", diff: 1 },
  { w: "SKATING", c: "Sport of gliding on blades or wheels", cat: "sports", diff: 1 },
  { w: "GYMNASTICS", c: "Sport of tumbling, beams, and rings", cat: "sports", diff: 1 },
  { w: "DIVING", c: "Sport of leaping from a platform into water", cat: "sports", diff: 1 },
  { w: "CYCLING", c: "Sport of racing on two wheels", cat: "sports", diff: 1 },
  { w: "TRIATHLON", c: "Race combining swimming, cycling, and running", cat: "sports", diff: 2 },
  { w: "DECATHLON", c: "Ten-event track and field competition", cat: "sports", diff: 3 },
  { w: "UMPIRE", c: "Official who makes the calls in baseball", cat: "sports", diff: 2 },
  { w: "CAPTAIN", c: "The player leading a sports team", cat: "sports", diff: 1 },
  { w: "ROSTER", c: "The full list of players on a team", cat: "sports", diff: 2 },
  { w: "TIMEOUT", c: "A brief pause called during play", cat: "sports", diff: 1 },
  { w: "OVERTIME", c: "Extra playing time after a tie", cat: "sports", diff: 1 },
  { w: "PENALTY", c: "A punishment for breaking the rules of play", cat: "sports", diff: 1 },
  { w: "FOUL", c: "A rule violation during play", cat: "sports", diff: 1 },
  { w: "SCOREBOARD", c: "Display showing the current score", cat: "sports", diff: 1 },
  { w: "JERSEY", c: "A team's uniform shirt", cat: "sports", diff: 1 },
  { w: "HELMET", c: "Protective headgear worn in contact sports", cat: "sports", diff: 1 },
  { w: "WHISTLE", c: "What a referee blows to stop play", cat: "sports", diff: 1 },

  // ---- science (batch 2) ----
  { w: "GRAVITY", c: "Force pulling objects toward each other", cat: "science", diff: 1 },
  { w: "FRICTION", c: "Force that resists sliding motion", cat: "science", diff: 2 },
  { w: "VELOCITY", c: "Speed in a given direction", cat: "science", diff: 2 },
  { w: "MOMENTUM", c: "Mass in motion", cat: "science", diff: 2 },
  { w: "DENSITY", c: "Mass packed into a given volume", cat: "science", diff: 2 },
  { w: "PRESSURE", c: "Force applied over an area", cat: "science", diff: 2 },
  { w: "ELEMENT", c: "A substance made of only one type of atom", cat: "science", diff: 1 },
  { w: "ISOTOPE", c: "A variant of an element with a different neutron count", cat: "science", diff: 3 },
  { w: "CATALYST", c: "A substance that speeds a reaction without being used up", cat: "science", diff: 3 },
  { w: "SOLUTION", c: "A mixture where one substance dissolves in another", cat: "science", diff: 2 },
  { w: "COMPOUND", c: "A substance formed from two or more elements", cat: "science", diff: 2 },
  { w: "NUCLEUS", c: "The dense center of an atom or a cell", cat: "science", diff: 2 },
  { w: "CHROMOSOME", c: "A structure carrying an organism's genes", cat: "science", diff: 3 },
  { w: "PHOTOSYNTHESIS", c: "Process plants use to turn sunlight into energy", cat: "science", diff: 2 },
  { w: "EVOLUTION", c: "Gradual change in species over generations", cat: "science", diff: 2 },
  { w: "ECOSYSTEM", c: "A community of organisms and their environment", cat: "science", diff: 2 },
  { w: "PREDATOR", c: "An animal that hunts others for food", cat: "science", diff: 1 },
  { w: "CAMOUFLAGE", c: "Coloring that helps an animal blend in", cat: "science", diff: 1 },
  { w: "HIBERNATE", c: "Spend winter in a dormant, low-energy state", cat: "science", diff: 2 },
  { w: "METAMORPHOSIS", c: "Dramatic change in form, like caterpillar to butterfly", cat: "science", diff: 2 },
  { w: "ASTEROID", c: "A rocky body orbiting the sun, smaller than a planet", cat: "science", diff: 1 },
  { w: "METEOR", c: "A \"shooting star\" burning up in the atmosphere", cat: "science", diff: 1 },
  { w: "NEBULA", c: "A cloud of gas and dust in space", cat: "science", diff: 2 },
  { w: "SATELLITE", c: "An object orbiting a planet or star", cat: "science", diff: 1 },
  { w: "GRAVITYWELL", c: "The dip a massive object creates in spacetime", cat: "science", diff: 3 },
  { w: "THERMOMETER", c: "Instrument for measuring temperature", cat: "science", diff: 1 },
  { w: "BAROMETER", c: "Instrument for measuring air pressure", cat: "science", diff: 3 },

  // ---- food (batch 2) ----
  { w: "LASAGNA", c: "Layered baked pasta dish", cat: "food", diff: 2 },
  { w: "BURRITO", c: "Rolled tortilla stuffed with fillings", cat: "food", diff: 1 },
  { w: "QUESADILLA", c: "Grilled, folded tortilla with melted cheese", cat: "food", diff: 2 },
  { w: "FALAFEL", c: "Fried chickpea patty popular in the Middle East", cat: "food", diff: 3 },
  { w: "HUMMUS", c: "Chickpea and tahini dip", cat: "food", diff: 2 },
  { w: "GUACAMOLE", c: "Mashed avocado dip", cat: "food", diff: 1 },
  { w: "SALSA", c: "Chunky tomato-based dip or sauce", cat: "food", diff: 1 },
  { w: "PESTO", c: "Sauce made from basil, pine nuts, and oil", cat: "food", diff: 2 },
  { w: "MARINARA", c: "Simple tomato-based pasta sauce", cat: "food", diff: 2 },
  { w: "ALFREDO", c: "Creamy white pasta sauce", cat: "food", diff: 2 },
  { w: "TERIYAKI", c: "Sweet soy-based Japanese glaze", cat: "food", diff: 2 },
  { w: "WASABI", c: "Sharp green Japanese condiment", cat: "food", diff: 2 },
  { w: "TOFU", c: "Soybean curd used as a meat substitute", cat: "food", diff: 1 },
  { w: "QUINOA", c: "Protein-rich grain-like seed", cat: "food", diff: 2 },
  { w: "OATMEAL", c: "Warm breakfast porridge made from oats", cat: "food", diff: 1 },
  { w: "GRANOLA", c: "Crunchy oat-and-honey breakfast mix", cat: "food", diff: 1 },
  { w: "SMOOTHIE", c: "Blended fruit drink", cat: "food", diff: 1 },
  { w: "MILKSHAKE", c: "Blended ice cream drink", cat: "food", diff: 1 },
  { w: "LEMONADE", c: "Classic sweet-and-tart summer drink", cat: "food", diff: 1 },
  { w: "ESPRESSO", c: "Strong, concentrated shot of coffee", cat: "food", diff: 2 },
  { w: "LATTE", c: "Espresso with steamed milk", cat: "food", diff: 1 },
  { w: "BISCUIT", c: "Soft, flaky quick bread", cat: "food", diff: 1 },
  { w: "MUFFIN", c: "Single-serving quick bread, often with fruit", cat: "food", diff: 1 },
  { w: "DONUT", c: "Fried, ring-shaped sweet treat", cat: "food", diff: 1 },
  { w: "BROWNIE", c: "Dense, fudgy chocolate baked square", cat: "food", diff: 1 },
  { w: "SORBET", c: "Frozen fruit dessert without dairy", cat: "food", diff: 2 },
  { w: "MERINGUE", c: "Crisp dessert made from whipped egg whites and sugar", cat: "food", diff: 3 },
  { w: "TRUFFLE", c: "Rich chocolate confection, or a prized underground fungus", cat: "food", diff: 3 },

  // ---- kids (batch 2) ----
  { w: "BALLOON", c: "Inflatable float at a birthday party", cat: "kids", diff: 1 },
  { w: "CONFETTI", c: "Small paper bits tossed to celebrate", cat: "kids", diff: 1 },
  { w: "PRESENT", c: "A wrapped birthday or holiday gift", cat: "kids", diff: 1 },
  { w: "CANDLE", c: "What you blow out on a birthday cake", cat: "kids", diff: 1 },
  { w: "LULLABY", c: "A soft song sung to help a baby sleep", cat: "kids", diff: 2 },
  { w: "BLANKET", c: "Cozy cover for bedtime", cat: "kids", diff: 1 },
  { w: "PILLOW", c: "Soft cushion for your head", cat: "kids", diff: 1 },
  { w: "CRAYONS", c: "A box of waxy coloring sticks", cat: "kids", diff: 1 },
  { w: "STICKER", c: "A small adhesive picture", cat: "kids", diff: 1 },
  { w: "SEESAW", c: "Playground plank that tips up and down", cat: "kids", diff: 1 },
  { w: "TRAMPOLINE", c: "Bouncy mesh you jump on", cat: "kids", diff: 1 },
  { w: "SANDCASTLE", c: "A beach structure built with a bucket and shovel", cat: "kids", diff: 1 },
  { w: "KITE", c: "A flying toy on a string", cat: "kids", diff: 1 },
  { w: "MARBLES", c: "Small glass balls used in a classic game", cat: "kids", diff: 1 },
  { w: "PUPPET", c: "A hand-operated toy character", cat: "kids", diff: 1 },
  { w: "TRICYCLE", c: "A three-wheeled ride for a small child", cat: "kids", diff: 1 },
  { w: "SCOOTER", c: "A two-wheeled ride you push with one foot", cat: "kids", diff: 1 },
  { w: "TREEHOUSE", c: "A play structure built up in the branches", cat: "kids", diff: 1 },
  { w: "FAIRY", c: "A tiny, magical winged creature", cat: "kids", diff: 1 },
  { w: "GOBLIN", c: "A mischievous fairy-tale creature", cat: "kids", diff: 1 },
  { w: "GIANT", c: "An enormous fairy-tale creature", cat: "kids", diff: 1 },
  { w: "TREASURE", c: "What a pirate buries and digs up", cat: "kids", diff: 1 },
  { w: "COMPASS", c: "What a pirate uses to find treasure", cat: "kids", diff: 1 },
  { w: "CASTLE", c: "Where a knight might live", cat: "kids", diff: 1 },
  { w: "CAPE", c: "What a superhero wears while flying", cat: "kids", diff: 1 },
  { w: "MASK", c: "What a superhero wears to hide their identity", cat: "kids", diff: 1 },

  // ---- general (batch 2, extra short/medium fill words for tighter grids) ----
  { w: "ARROW", c: "Pointed shaft shot from a bow", cat: "general", diff: 1 },
  { w: "SHIELD", c: "Protective barrier held up in defense", cat: "general", diff: 1 },
  { w: "MIRAGE", c: "An illusion caused by heat and light", cat: "general", diff: 2 },
  { w: "ECHO", c: "Repeated sound bouncing off a surface", cat: "general", diff: 1 },
  { w: "SHADOW", c: "Dark shape cast by blocked light", cat: "general", diff: 1 },
  { w: "RIPPLE", c: "A small wave spreading outward", cat: "general", diff: 1 },
  { w: "BREEZE", c: "A gentle wind", cat: "general", diff: 1 },
  { w: "FLAME", c: "The visible part of a fire", cat: "general", diff: 1 },
  { w: "EMBER", c: "A glowing piece of coal or wood", cat: "general", diff: 2 },
  { w: "SPARK", c: "A tiny flash of fire or electricity", cat: "general", diff: 1 },
  { w: "FROST", c: "A thin layer of ice crystals", cat: "general", diff: 1 },
  { w: "PUDDLE", c: "A small pool of water after rain", cat: "general", diff: 1 },
  { w: "MEADOW", c: "An open grassy field", cat: "general", diff: 1 },
  { w: "ORCHARD", c: "A cultivated area of fruit trees", cat: "general", diff: 2 },
  { w: "HARVEST", c: "The gathering of ripe crops", cat: "general", diff: 1 },
  { w: "COMPASS", c: "A tool used to find direction", cat: "general", diff: 1 },
  { w: "LANTERN", c: "A portable light in a case", cat: "general", diff: 1 },
  { w: "CANDLE", c: "A wax stick with a burning wick", cat: "general", diff: 1 },
  { w: "MELODY", c: "A pleasing sequence of musical notes", cat: "general", diff: 1 },
  { w: "RHYTHM", c: "A repeated pattern of beats", cat: "general", diff: 1 },
  { w: "WHISTLE", c: "A high-pitched sound made by blowing air", cat: "general", diff: 1 },
  { w: "PUZZLE", c: "A problem designed to test cleverness", cat: "general", diff: 1 },
  { w: "RIDDLE", c: "A clever question with a tricky answer", cat: "general", diff: 1 },
  { w: "MYSTERY", c: "Something unexplained or puzzling", cat: "general", diff: 1 },
  { w: "ADVENTURE", c: "An exciting or daring journey", cat: "general", diff: 1 },
  { w: "COURAGE", c: "The strength to face fear", cat: "general", diff: 1 },
  { w: "PATIENCE", c: "The ability to wait calmly", cat: "general", diff: 2 },
  { w: "HONESTY", c: "The quality of telling the truth", cat: "general", diff: 2 },
  { w: "KINDNESS", c: "The quality of being gentle and caring", cat: "general", diff: 1 },
  { w: "AGO", c: "In the past", cat: "general", diff: 1 },
  { w: "END", c: "The final part of something", cat: "general", diff: 1 },
  { w: "TOP", c: "The highest point", cat: "general", diff: 1 },
  { w: "OLD", c: "Not young or new", cat: "general", diff: 1 },
  { w: "NEW", c: "Recently made or begun", cat: "general", diff: 1 },
  { w: "BIG", c: "Large in size", cat: "general", diff: 1 },
  { w: "RUN", c: "Move quickly on foot", cat: "general", diff: 1 },
  { w: "JOG", c: "Run at a steady, gentle pace", cat: "general", diff: 1 },
  { w: "HOP", c: "Jump on one or both feet", cat: "general", diff: 1 },
  { w: "SIT", c: "Rest on a chair or the ground", cat: "general", diff: 1 },
  { w: "NAP", c: "A short daytime sleep", cat: "general", diff: 1 },
  { w: "FAN", c: "A device that moves air, or an enthusiastic supporter", cat: "general", diff: 1 },
  { w: "JAR", c: "A glass container with a lid", cat: "general", diff: 1 },
  { w: "LID", c: "A cover for a container", cat: "general", diff: 1 },
  { w: "TIN", c: "A small metal container", cat: "general", diff: 1 },
  { w: "WEB", c: "What a spider spins", cat: "general", diff: 1 },
  { w: "NET", c: "Woven mesh used to catch things", cat: "general", diff: 1 },
  { w: "ROPE", c: "Thick, twisted cord", cat: "general", diff: 1 },
  { w: "KNOT", c: "A fastening made by looping rope or string", cat: "general", diff: 1 },
  { w: "NAIL", c: "A thin metal spike hammered into wood", cat: "general", diff: 1 },
  { w: "SAW", c: "Tool used to cut wood", cat: "general", diff: 1 },
  { w: "AXE", c: "Tool with a blade for chopping wood", cat: "general", diff: 1 },
];
