// Across — crossword grid generator.
//
// Template-first, NYT-style density: a hardcoded set of symmetric block
// patterns fixes the fill ratio *before* any word is placed (70-85%+ white
// cells by construction), then a backtracking solver with MRV ordering and
// forward checking fills the slots from the word bank. This replaces the
// old greedy "place the longest word, then bolt more on wherever they fit"
// approach, which topped out around 50-60% fill because nothing forced the
// grid to stay dense.
//
// Cost control: this runs in a browser Web Worker so dense search cannot
// freeze typing or navigation. The solver is still bounded by both a step
// count and a wall-clock deadline, tries templates in shuffled order, and
// only accepts a fully-filled template.

export const SIZE_MAP = { mini: 5, quick: 7, compact: 9, standard: 11, large: 15 };
export const DIFFICULTY_PROFILES = {
  beginner: { maxDiff: 1, targetDiff: 1 },
  easy: { maxDiff: 2, targetDiff: 1 },
  medium: { maxDiff: 2, targetDiff: 2 },
  hard: { maxDiff: 3, targetDiff: 2.6 },
  expert: { maxDiff: 3, targetDiff: 3 },
};

// ---------------------------------------------------------------------
// 1. Symmetric block templates (180-degree rotational symmetry).
//    '.' = white/fillable, '#' = block. Each satisfies (validated by
//    validateTemplate, see test script): symmetric, single connected
//    white region, no white run <3 in either direction, every white cell
//    belongs to both an across and a down slot.
// ---------------------------------------------------------------------

// Generated by scripts/gen-templates.mjs, which builds valid symmetric
// templates *incrementally* (start from the all-white grid — always valid —
// and add one randomly-placed symmetric block-pair at a time, keeping each
// addition only if the template is still valid) rather than gambling on a
// single from-scratch random placement, which almost never satisfies the
// connectivity + min-run-length + full-coverage constraints simultaneously
// at 11x11/15x15 scale. Each candidate is additionally scored by
// "tightness" — how many same-length slots it demands versus how many
// words of that length the corpus actually has — and the lowest-tightness
// survivor per block count is kept. This matters: the original hand-written
// templates all leaned on 4-6 simultaneous 11-letter slots against a
// ~42-word pool for that length, which is *why* the backtracking solver
// below never found a solution within budget (empirically 0 successes in
// testing, not merely slow) — it wasn't a solver bug, it was structurally
// unsolvable-in-practice for this corpus. Re-run the script (and eyeball
// the printed tightness/fill numbers) if the corpus's length distribution
// changes significantly.
// The corpus now has ~9,100 unique usable 3-15-letter answers, up from ~4,600.
// These templates are intentionally unchanged: the expansion improves their
// candidate domains and prepares the separate, parked density pass without
// silently changing the app's current light block-cell layout language.
const TEMPLATES = {
  mini: [
    // blocks=4 fill=84% tightness=0.06 lens={"3":2,"4":4,"5":4}
    ["....#", "....#", ".....", "#....", "#...."],
  ],
  quick: [
    ["###...#", "##.....", ".......", ".......", ".......", ".....##", "#...###"],
    ["....###", "....###", "......#", ".......", "#......", "###....", "###...."],
    ["....###", ".....##", ".......", ".......", ".......", "##.....", "###...."],
    [".....##", "......#", "......#", ".......", "#......", "#......", "##....."],
  ],
  compact: [
    // 80% open; dominated by flexible 3–6 letter slots.
    ["...##....", "...#.....", "...#.....", "......###", "#.......#", "###......", ".....#...", ".....#...", "....##..."],
    [".....#...", ".....#...", ".....#...", "###......", "#.......#", "......###", "...#.....", "...#.....", "...#....."],
  ],
  standard: [
    // blocks=20 fill=83% tightness=0.35 lens={"3":4,"4":6,"5":4,"6":4,"9":2,"10":6,"11":4}
    ["####.....##", "#..........", "...........", "....#......", "....#.....#", "...........", "#.....#....", "......#....", "...........", "..........#", "##.....####"],
    // blocks=28 fill=77% tightness=0.35 lens={"3":6,"4":8,"5":4,"6":2,"7":4,"8":2,"9":2,"10":2,"11":2}
    ["...####....", ".....##....", "......#....", "##.........", "##........#", "##.......##", "#........##", ".........##", "....#......", "....##.....", "....####..."],
    // blocks=32 fill=74% tightness=0.36 lens={"3":7,"4":2,"5":6,"6":4,"7":2,"8":4,"9":2,"10":2,"11":1}
    ["###...#####", "###.......#", "#.........#", ".....#.....", "......#....", "...........", "....#......", ".....#.....", "#.........#", "#.......###", "#####...###"],
    // blocks=24 fill=80% tightness=0.38 lens={"3":6,"4":2,"5":2,"6":6,"7":4,"8":4,"9":2,"11":4}
    ["##.......##", "##........#", "#.........#", "......##...", "......#....", "...........", "....#......", "...##......", "#.........#", "#........##", "##.......##"],
    // blocks=26 fill=79% tightness=0.41 lens={"3":4,"4":6,"6":6,"7":6,"9":6,"11":2}
    ["###....####", "##.........", "##.........", "...#.......", "......#....", "...........", "....#......", ".......#...", ".........##", ".........##", "####....###"],
    // blocks=22 fill=82% tightness=0.43 lens={"3":6,"4":8,"6":6,"7":2,"8":2,"9":2,"10":2,"11":4}
    ["#####....##", "...#......#", "...........", "......#....", ".......#...", "...........", "...#.......", "....#......", "...........", "#......#...", "##....#####"],
  ],
  large: [
    // 80–83% open; long simultaneous anchors are deliberately avoided.
    ["#....##...#...#", "......#.......#", "......#........", "...#....##.....", "....##....##...", ".......#...#...", "......#....#...", "####.......####", "...#....#......", "...#...#.......", "...##....##....", ".....##....#...", "........#......", "#.......#......", "#...#...##....#"],
    ["......##......#", "......#........", "......#........", "#...#...###....", "#......##......", "...#...#...#...", ".....#......###", ".....#...#.....", "###......#.....", "...#...#...#...", "......##......#", "....###...#...#", "........#......", "........#......", "#......##......"],
    ["....##...#.....", ".....#.........", ".....#.........", "...#......#....", "...#...#...#...", ".......#...#...", "#...#...##.....", "###.........###", ".....##...#...#", "...#...#.......", "...#...#...#...", "....#......#...", ".........#.....", ".........#.....", ".....#...##...."],
  ],
};

// Validates every symmetry/connectivity/min-run-length/coverage invariant a
// template must satisfy. Exported so the test script can assert it holds
// for every hardcoded template above; not on the hot path at runtime.
export function validateTemplate(rows) {
  const n = rows.length;
  for (const row of rows) if (row.length !== n) return { ok: false, reason: "not square" };
  const isBlock = (r, c) => rows[r][c] === "#";

  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (isBlock(r, c) !== isBlock(n - 1 - r, n - 1 - c)) return { ok: false, reason: "asymmetric" };
    }
  }

  let total = 0;
  let start = null;
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (!isBlock(r, c)) {
        total++;
        if (!start) start = [r, c];
      }
    }
  }
  if (total === 0) return { ok: false, reason: "no white cells" };
  const seen = new Set([start[0] * n + start[1]]);
  const stack = [start];
  while (stack.length) {
    const [r, c] = stack.pop();
    for (const [dr, dc] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
      const nr = r + dr, nc = c + dc;
      if (nr < 0 || nr >= n || nc < 0 || nc >= n || isBlock(nr, nc)) continue;
      const key = nr * n + nc;
      if (seen.has(key)) continue;
      seen.add(key);
      stack.push([nr, nc]);
    }
  }
  if (seen.size !== total) return { ok: false, reason: "disconnected" };

  const acrossCover = new Set();
  const downCover = new Set();
  for (let r = 0; r < n; r++) {
    let runStart = null;
    for (let c = 0; c <= n; c++) {
      const white = c < n && !isBlock(r, c);
      if (white) {
        if (runStart === null) runStart = c;
      } else if (runStart !== null) {
        const len = c - runStart;
        if (len === 1 || len === 2) return { ok: false, reason: `short across run at row ${r}` };
        if (len >= 3) for (let cc = runStart; cc < c; cc++) acrossCover.add(r * n + cc);
        runStart = null;
      }
    }
  }
  for (let c = 0; c < n; c++) {
    let runStart = null;
    for (let r = 0; r <= n; r++) {
      const white = r < n && !isBlock(r, c);
      if (white) {
        if (runStart === null) runStart = r;
      } else if (runStart !== null) {
        const len = r - runStart;
        if (len === 1 || len === 2) return { ok: false, reason: `short down run at col ${c}` };
        if (len >= 3) for (let rr = runStart; rr < r; rr++) downCover.add(rr * n + c);
        runStart = null;
      }
    }
  }
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (!isBlock(r, c)) {
        const key = r * n + c;
        if (!acrossCover.has(key) || !downCover.has(key)) return { ok: false, reason: `cell ${r},${c} missing across/down slot` };
      }
    }
  }

  return { ok: true, whiteCount: total, blockCount: n * n - total };
}

// ---------------------------------------------------------------------
// 2. Slot extraction + crossing map
// ---------------------------------------------------------------------

export function extractSlots(rows) {
  const n = rows.length;
  const isBlock = (r, c) => rows[r][c] === "#";
  const slots = [];
  let id = 0;

  for (let r = 0; r < n; r++) {
    let c = 0;
    while (c < n) {
      if (isBlock(r, c)) { c++; continue; }
      const start = c;
      while (c < n && !isBlock(r, c)) c++;
      const len = c - start;
      if (len >= 3) {
        const cells = [];
        for (let i = 0; i < len; i++) cells.push([r, start + i]);
        slots.push({ id: id++, direction: "across", row: r, col: start, length: len, cells, crossings: new Array(len).fill(null) });
      }
    }
  }
  for (let c = 0; c < n; c++) {
    let r = 0;
    while (r < n) {
      if (isBlock(r, c)) { r++; continue; }
      const start = r;
      while (r < n && !isBlock(r, c)) r++;
      const len = r - start;
      if (len >= 3) {
        const cells = [];
        for (let i = 0; i < len; i++) cells.push([start + i, c]);
        slots.push({ id: id++, direction: "down", row: start, col: c, length: len, cells, crossings: new Array(len).fill(null) });
      }
    }
  }

  const cellMap = new Map();
  for (const slot of slots) {
    slot.cells.forEach(([r, c], idx) => {
      const key = r * n + c;
      let entry = cellMap.get(key);
      if (!entry) { entry = {}; cellMap.set(key, entry); }
      entry[slot.direction] = { slotId: slot.id, idx };
    });
  }
  for (const entry of cellMap.values()) {
    if (entry.across && entry.down) {
      const a = slots[entry.across.slotId];
      const d = slots[entry.down.slotId];
      a.crossings[entry.across.idx] = { otherSlotId: d.id, theirIndex: entry.down.idx };
      d.crossings[entry.down.idx] = { otherSlotId: a.id, theirIndex: entry.across.idx };
    }
  }

  return slots;
}

// The longest ~30% of slots get strong theme preference; the rest are
// treated as ordinary short fill and may draw from the whole corpus.
export function computeLongSlotIds(slots) {
  const sorted = [...slots].sort((a, b) => b.length - a.length);
  const count = Math.max(1, Math.round(sorted.length * 0.3));
  return new Set(sorted.slice(0, count).map((s) => s.id));
}

// ---------------------------------------------------------------------
// 3 + 4. Word index + theme scoring
// ---------------------------------------------------------------------

const STOPWORDS = new Set(["the", "and", "for", "with", "from", "that", "this", "are", "was", "were", "your", "you", "its", "into", "onto", "our"]);

function tokenize(str) {
  return (str || "")
    .toLowerCase()
    .split(/\s+/)
    .filter((t) => t.length >= 3 && !STOPWORDS.has(t));
}

// Naive-singular handling ("capitals" -> also matches "capital") reused
// from the original buildCandidateGroups tokenization logic.
function withSingulars(tokens) {
  return [...new Set(tokens.flatMap((t) => (t.endsWith("s") && t.length > 4 ? [t, t.slice(0, -1)] : [t])))];
}

// Builds the deduped, size/difficulty-filtered candidate pool, scored by
// theme relevance: title tokens match (tier 2) > category/keyword match
// (tier 1) > general (tier 0). Crucially, nothing is *excluded* by
// relevance — tier only affects ordering — so a narrow topic never starves
// the grid of fill words the way the old keyword-filtered pool could.
export function buildCandidatePool(wordBank, keywords, title, maxDiff, n) {
  const seen = new Set();
  const all = [];
  for (const entry of wordBank) {
    const w = entry.w.toUpperCase();
    if (!/^[A-Z]+$/.test(w)) continue;
    if (w.length < 3 || w.length > n) continue;
    if (entry.diff > maxDiff) continue;
    if (seen.has(w)) continue;
    seen.add(w);
    all.push({ word: w, clue: entry.c, cat: (entry.cat || "").toLowerCase(), diff: entry.diff || 1, tier: 0 });
  }

  const categoryTokens = withSingulars(tokenize((keywords || []).join(" ")));
  const titleTokens = withSingulars(tokenize(title));

  for (const e of all) {
    const hay = `${e.word.toLowerCase()} ${e.clue.toLowerCase()} ${e.cat}`;
    const titleHit = titleTokens.length > 0 && titleTokens.some((t) => hay.includes(t));
    const catHit = categoryTokens.length > 0 && categoryTokens.some((t) => hay.includes(t));
    e.tier = titleHit ? 2 : catHit ? 1 : 0;
  }

  return all;
}

export function buildWordIndex(entries) {
  const byLength = new Map();
  const byLenPosLetter = new Map();
  for (const e of entries) {
    const len = e.word.length;
    if (!byLength.has(len)) byLength.set(len, []);
    byLength.get(len).push(e);
    for (let i = 0; i < len; i++) {
      const key = `${len}:${i}:${e.word[i]}`;
      if (!byLenPosLetter.has(key)) byLenPosLetter.set(key, []);
      byLenPosLetter.get(key).push(e);
    }
  }
  return { byLength, byLenPosLetter };
}

// ---------------------------------------------------------------------
// 2b. Arc-consistency preprocessing (AC-3-lite)
//
// Before any word gets placed, prune each slot's candidate domain down to
// only words that have *some* supporting match in every crossing slot's
// domain, and repeat until nothing more can be removed. Without this, plain
// backtracking with only forward-checking regularly reached 90%+ of the way
// through a grid and then died on a single slot needing an letter-position
// combination (e.g. a 4-letter word starting "TRE") that plain doesn't
// exist in this word bank — a dead end that arc consistency rules out
// *before* search starts, instead of search discovering it empirically deep
// in the tree, over and over, across thousands of restarts. This is the
// standard AC-3 algorithm restricted to this problem's binary constraints
// (one shared letter per crossing pair), which keeps it cheap: cost is
// roughly iterations x slots x domain-size x crossings, all O(1) set
// lookups, not the exponential cost backtracking search has.
export function pruneDomains(slots, index) {
  const domains = new Map();
  for (const slot of slots) domains.set(slot.id, (index.byLength.get(slot.length) || []).slice());

  let changed = true;
  let iterations = 0;
  const MAX_ITERATIONS = 6;
  while (changed && iterations < MAX_ITERATIONS) {
    changed = false;
    iterations++;

    // Letter-present-at-position sets, derived from the *current* (possibly
    // already-pruned) domains — recomputed each round so a removal in one
    // slot can cascade into further removals elsewhere on the next pass.
    const letterSets = new Map();
    for (const slot of slots) {
      const dom = domains.get(slot.id);
      const sets = Array.from({ length: slot.length }, () => new Set());
      for (const e of dom) for (let i = 0; i < slot.length; i++) sets[i].add(e.word[i]);
      letterSets.set(slot.id, sets);
    }

    for (const slot of slots) {
      const dom = domains.get(slot.id);
      const kept = [];
      for (const entry of dom) {
        let ok = true;
        for (let i = 0; i < slot.length; i++) {
          const cross = slot.crossings[i];
          if (!cross) continue;
          const otherSets = letterSets.get(cross.otherSlotId);
          if (!otherSets[cross.theirIndex].has(entry.word[i])) {
            ok = false;
            break;
          }
        }
        if (ok) kept.push(entry);
      }
      if (kept.length !== dom.length) {
        domains.set(slot.id, kept);
        changed = true;
      }
    }
  }

  return domains;
}

// Maintain arc consistency throughout search, rather than only once before
// it starts. Dense crossword fill is dominated by constraints that travel
// through several still-empty crossings; checking only the word directly
// beside the last placement discovers those contradictions far too late.
// Domains are restored from a compact trail on backtrack so this remains
// practical for the 15x15 grid in a browser worker.
export function runMaintainingArcConsistencyFill(slots, initialDomains, longIds, deadline, targetDiff = 2) {
  const domains = new Map([...initialDomains].map(([id, items]) => [id, items.slice()]));
  const assignment = new Array(slots.length).fill(null);
  const usedWords = new Set();
  let steps = 0;
  const STEP_LIMIT = 3000000;

  function budgetOk() {
    steps++;
    return steps <= STEP_LIMIT && Date.now() <= deadline;
  }

  function restore(trail) {
    for (let i = trail.length - 1; i >= 0; i--) domains.set(trail[i][0], trail[i][1]);
  }

  function replaceDomain(id, next, trail) {
    const previous = domains.get(id);
    if (previous === next) return;
    trail.push([id, previous]);
    domains.set(id, next);
  }

  function liveDomain(slot) {
    const items = domains.get(slot.id) || [];
    if (usedWords.size === 0 || assignment[slot.id]) return items;
    return items.filter((entry) => !usedWords.has(entry.word));
  }

  // Repeatedly remove values without support at a crossing. Assigned slots
  // have singleton domains, so their letters automatically propagate across
  // the rest of the grid. A short global pass is faster here than maintaining
  // a large JS object queue for every arc.
  function propagate(trail) {
    let changed = true;
    let rounds = 0;
    while (changed && rounds++ < 12) {
      if (!budgetOk()) return false;
      changed = false;
      const letterSets = new Map();
      for (const slot of slots) {
        const sets = Array.from({ length: slot.length }, () => new Set());
        for (const entry of liveDomain(slot)) {
          for (let i = 0; i < slot.length; i++) sets[i].add(entry.word[i]);
        }
        letterSets.set(slot.id, sets);
      }

      for (const slot of slots) {
        if (assignment[slot.id]) continue;
        const current = liveDomain(slot);
        if (current.length === 0) return false;
        const kept = current.filter((entry) => {
          for (let i = 0; i < slot.length; i++) {
            const cross = slot.crossings[i];
            if (!cross) continue;
            if (!letterSets.get(cross.otherSlotId)[cross.theirIndex].has(entry.word[i])) return false;
          }
          return true;
        });
        if (kept.length === 0) return false;
        if (kept.length !== (domains.get(slot.id) || []).length) {
          replaceDomain(slot.id, kept, trail);
          changed = true;
        }
      }
    }
    return true;
  }

  function selectSlot() {
    let best = null;
    let bestItems = null;
    for (const slot of slots) {
      if (assignment[slot.id]) continue;
      const items = liveDomain(slot);
      if (items.length === 0) return { slot, items };
      if (!best || items.length < bestItems.length || (items.length === bestItems.length && slot.length > best.length)) {
        best = slot;
        bestItems = items;
      }
    }
    return best ? { slot: best, items: bestItems } : null;
  }

  function orderedCandidates(slot, items) {
    const themed = longIds.has(slot.id);
    const supportByIndex = slot.crossings.map((cross) => {
      if (!cross || assignment[cross.otherSlotId]) return null;
      const counts = new Map();
      for (const candidate of liveDomain(slots[cross.otherSlotId])) {
        const letter = candidate.word[cross.theirIndex];
        counts.set(letter, (counts.get(letter) || 0) + 1);
      }
      return counts;
    });
    const supportScore = (entry) => {
      let score = 0;
      for (let i = 0; i < supportByIndex.length; i++) {
        const counts = supportByIndex[i];
        if (counts) score += Math.log1p(counts.get(entry.word[i]) || 0);
      }
      return score;
    };
    return shuffleInPlace(items.slice()).sort((a, b) => {
      // Category relevance leads in every slot; the more specific title tier
      // gets extra priority in the longest slots. Crossing support still
      // breaks ties, so generic high-support fill remains available whenever
      // the theme corpus cannot satisfy an interlock.
      const aThemeTier = themed ? a.tier : Math.min(a.tier, 1);
      const bThemeTier = themed ? b.tier : Math.min(b.tier, 1);
      if (aThemeTier !== bThemeTier) return bThemeTier - aThemeTier;
      const supportDelta = supportScore(b) - supportScore(a);
      if (Math.abs(supportDelta) > 0.0001) return supportDelta;
      return Math.abs(a.diff - targetDiff) - Math.abs(b.diff - targetDiff);
    });
  }

  function solve() {
    if (!budgetOk()) return false;
    const selected = selectSlot();
    if (!selected) return true;
    if (selected.items.length === 0) return false;

    const candidates = orderedCandidates(selected.slot, selected.items);
    for (const entry of candidates) {
      if (!budgetOk()) return false;
      const trail = [];
      assignment[selected.slot.id] = entry;
      usedWords.add(entry.word);
      replaceDomain(selected.slot.id, [entry], trail);
      if (propagate(trail) && solve()) return true;
      assignment[selected.slot.id] = null;
      usedWords.delete(entry.word);
      restore(trail);
    }
    return false;
  }

  return solve() ? { success: true, assignment } : { success: false, assignment: null };
}

// ---------------------------------------------------------------------
// 3. Backtracking fill with MRV + forward checking
// ---------------------------------------------------------------------

const CANDIDATE_CAP = 60;
const STEP_BUDGET_PER_TEMPLATE = 600000;
// A single DFS attempt can get stuck deep in a subtree that "looks"
// promising (lots of locally-valid partial assignments) but has no complete
// solution, and burn the *entire* shared step budget without ever
// backtracking out far enough to try a different top-level word. Capping
// steps per attempt forces a fresh reshuffle — a cheap, different dice
// roll — instead of over-investing in one unlucky branch. This is the
// standard "restart with cutoff" strategy for hard CSP search.
const STEPS_PER_ATTEMPT = 6000;

function shuffleInPlace(arr) {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
}

// Runs the backtracking DFS, restarting with a freshly-shuffled candidate
// order whenever a full attempt exhausts its search tree without finding a
// solution. A single DFS attempt on a tightly-constrained grid (e.g. a
// wide-open mini template) can dead-end after visiting only a few dozen
// nodes — far short of the step budget — simply because the top-level
// slot's candidate cap (14) didn't happen to include a workable word this
// shuffle. Restarting with a new shuffle is what actually spends the rest
// of the budget productively, the same way random-restart search does for
// any CSP with a large but not-fully-explorable branching factor.
export function runBacktrackFill(slots, index, longIds, deadline, domains, targetDiff = 2) {
  let steps = 0; // shared across restarts, bounds total work for this template
  let aborted = false; // budget fully exhausted — stop restarting entirely
  let attemptSteps = 0; // steps used by the current attempt only

  function budgetOk() {
    steps++;
    attemptSteps++;
    if (steps > STEP_BUDGET_PER_TEMPLATE || Date.now() > deadline) {
      aborted = true;
      return false;
    }
    if (attemptSteps > STEPS_PER_ATTEMPT) return false; // cut this attempt short, try a fresh shuffle
    return true;
  }

  // One DFS attempt with a fresh, freshly-shuffled assignment. Returns the
  // filled assignment array on success, or null if this attempt's search
  // tree was exhausted (cutoff or otherwise) without a solution.
  function attempt() {
    attemptSteps = 0;
    const assignment = new Array(slots.length).fill(null);
    const usedWords = new Set();
    // Candidate-count cache, keyed by slot id, invalidated only for the
    // slots whose fixed letters actually changed (i.e. the crossings of
    // whichever slot was just assigned/unassigned). Without this, MRV
    // selection would recompute candidatesFor() for every unfilled slot on
    // every node — O(slots) full recomputations per step — which is by far
    // the dominant cost and made real backtracking depth unreachable within
    // budget. With it, an assign/unassign only touches that slot's actual
    // crossings (typically a handful), the same locality forward-checking
    // already relies on.
    const candCache = new Map();

    function invalidateCrossingsOf(slot) {
      for (let i = 0; i < slot.length; i++) {
        const cross = slot.crossings[i];
        if (cross) candCache.delete(cross.otherSlotId);
      }
    }

    function fixedLettersFor(slot) {
      const letters = new Array(slot.length).fill(null);
      for (let i = 0; i < slot.length; i++) {
        const cross = slot.crossings[i];
        if (!cross) continue;
        const other = assignment[cross.otherSlotId];
        if (other) letters[i] = other.word[cross.theirIndex];
      }
      return letters;
    }

    function matchesFixed(word, letters) {
      for (let i = 0; i < letters.length; i++) {
        if (letters[i] && word[i] !== letters[i]) return false;
      }
      return true;
    }

    // Matches for a slot's currently-fixed letters, ignoring which words are
    // already used elsewhere in the grid — this is what gets cached, since
    // it only depends on crossing letters (invalidated precisely on those).
    // usedWords is filtered separately at lookup time (cheap: a pass over
    // an already letter-narrowed list) so the cache never goes stale when
    // some unrelated slot uses/frees a word.
    function lettersMatchesFor(slot) {
      const letters = fixedLettersFor(slot);
      const fixedPositions = [];
      for (let i = 0; i < letters.length; i++) if (letters[i]) fixedPositions.push(i);

      let base;
      if (fixedPositions.length === 0) {
        // Arc-consistency-pruned domain, not the raw length bucket — see
        // pruneDomains. Falls back to the raw bucket if no domains map was
        // passed in (keeps this function usable standalone/in tests).
        base = (domains ? domains.get(slot.id) : null) || index.byLength.get(slot.length) || [];
      } else {
        const lists = fixedPositions
          .map((i) => index.byLenPosLetter.get(`${slot.length}:${i}:${letters[i]}`) || [])
          .sort((a, b) => a.length - b.length);
        base = lists[0];
        for (let k = 1; k < lists.length && base.length > 0; k++) {
          const s = new Set(lists[k]);
          base = base.filter((e) => s.has(e));
        }
      }

      const out = [];
      for (const e of base) {
        if (!matchesFixed(e.word, letters)) continue;
        out.push(e);
      }
      return out;
    }

    function getLetterMatches(slot) {
      const cached = candCache.get(slot.id);
      if (cached) return cached;
      const c = lettersMatchesFor(slot);
      candCache.set(slot.id, c);
      return c;
    }

    function getCandidates(slot) {
      const matches = getLetterMatches(slot);
      if (usedWords.size === 0) return matches;
      const out = [];
      for (const e of matches) {
        if (!usedWords.has(e.word)) out.push(e);
      }
      return out;
    }

    function orderCandidates(slot, candidates) {
      const byDifficulty = (items) => shuffleInPlace(items.slice()).sort((a, b) => Math.abs(a.diff - targetDiff) - Math.abs(b.diff - targetDiff));
      if (longIds.has(slot.id)) {
        const t2 = [], t1 = [], t0 = [];
        for (const e of candidates) (e.tier === 2 ? t2 : e.tier === 1 ? t1 : t0).push(e);
        return [...byDifficulty(t2), ...byDifficulty(t1), ...byDifficulty(t0)];
      }
      return byDifficulty(candidates);
    }

    function selectSlot() {
      let best = null;
      let bestCandidates = null;
      let bestCount = Infinity;
      for (const slot of slots) {
        if (assignment[slot.id] !== null) continue;
        const cands = getCandidates(slot);
        if (cands.length === 0) {
          return { slot, candidates: cands, deadEnd: true };
        }
        if (cands.length < bestCount) {
          bestCount = cands.length;
          best = slot;
          bestCandidates = cands;
        }
      }
      if (!best) return null; // all slots filled
      return { slot: best, candidates: bestCandidates, deadEnd: false };
    }

    function forwardCheckOk(justFilled) {
      for (let i = 0; i < justFilled.length; i++) {
        const cross = justFilled.crossings[i];
        if (!cross) continue;
        const other = slots[cross.otherSlotId];
        if (assignment[other.id]) continue;
        if (getCandidates(other).length === 0) return false;
      }
      return true;
    }

    function solve() {
      if (!budgetOk()) return false;
      const sel = selectSlot();
      if (sel === null) return true; // every slot filled
      if (sel.deadEnd) return false;

      const ordered = orderCandidates(sel.slot, sel.candidates);
      const cap = Math.min(ordered.length, CANDIDATE_CAP);
      for (let i = 0; i < cap; i++) {
        const entry = ordered[i];
        assignment[sel.slot.id] = entry;
        usedWords.add(entry.word);
        invalidateCrossingsOf(sel.slot);
        if (forwardCheckOk(sel.slot) && solve()) return true;
        assignment[sel.slot.id] = null;
        usedWords.delete(entry.word);
        invalidateCrossingsOf(sel.slot);
        if (aborted) return false;
      }
      return false;
    }

    return solve() ? assignment : null;
  }

  // Random-restart loop: a single DFS attempt on a tightly-constrained grid
  // (e.g. a wide-open mini template) can exhaust its whole search tree
  // after only a few dozen nodes — far short of the step budget — simply
  // because the root slot's capped candidate sample (CANDIDATE_CAP) didn't
  // happen to include a workable word this shuffle. Restarting with a
  // freshly-shuffled order spends the rest of the budget productively,
  // the same way random-restart search does for any CSP whose branching
  // factor is too large to fully explore.
  const MAX_RESTARTS = 5000;
  for (let r = 0; r < MAX_RESTARTS && !aborted && Date.now() <= deadline; r++) {
    const result = attempt();
    if (result) return { success: true, assignment: result };
  }
  return { success: false, assignment: null };
}

function buildOutputFromSlots(rows, slots, assignment, n) {
  const isBlock = (r, c) => rows[r][c] === "#";
  const startKeys = new Set();
  for (const slot of slots) startKeys.add(`${slot.row},${slot.col}`);

  const cells = [];
  const numberAt = new Map();
  let next = 1;
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      const block = isBlock(r, c);
      let number = null;
      if (!block && startKeys.has(`${r},${c}`)) {
        number = next++;
        numberAt.set(`${r},${c}`, number);
      }
      cells.push({ row: r, col: c, letter: null, block, number });
    }
  }
  for (const slot of slots) {
    const entry = assignment[slot.id];
    for (let i = 0; i < slot.length; i++) {
      const [r, c] = slot.cells[i];
      cells[r * n + c].letter = entry.word[i];
    }
  }

  const words = slots
    .map((slot) => {
      const entry = assignment[slot.id];
      return {
        number: numberAt.get(`${slot.row},${slot.col}`) ?? null,
        direction: slot.direction,
        answer: entry.word,
        clue: entry.clue,
        row: slot.row,
        col: slot.col,
        length: slot.length,
        cells: slot.cells.map(([r, c]) => [r, c]),
      };
    })
    .sort((a, b) => a.number - b.number || (a.direction === "across" ? 0 : 1) - (b.direction === "across" ? 0 : 1));

  return { rows: n, cols: n, cells, words };
}

// ---------------------------------------------------------------------
// Top-level entry point
// ---------------------------------------------------------------------

const TIME_BUDGET_MS = { mini: 2500, compact: 12000, large: 2500 };
const MIN_OPEN_RATIO = { mini: 0.80, compact: 0.80, large: 0.60 };

function openCellRatio(grid) {
  const cells = grid?.cells || [];
  return cells.length ? cells.filter((cell) => !cell.block).length / cells.length : 0;
}

export function generatePuzzle({ keywords = [], title = "", size = "standard", difficulty = "medium", wordBank }) {
  const n = SIZE_MAP[size] || SIZE_MAP.standard;
  const profile = DIFFICULTY_PROFILES[difficulty] || DIFFICULTY_PROFILES.medium;
  const maxDiff = profile.maxDiff;

  const pool = buildCandidatePool(wordBank, keywords, title, maxDiff, n);
  const index = buildWordIndex(pool);

  const templates = shuffleInPlace([...(TEMPLATES[size] || TEMPLATES.standard)]);
  const timeBudget = TIME_BUDGET_MS[size] || 5000;
  const minimumDensity = MIN_OPEN_RATIO[size] || 0;
  const overallDeadline = Date.now() + timeBudget;
  // Each template gets its own fair slice of the total budget — critical,
  // because template difficulty varies wildly for a given word pool (two
  // templates that both validate fine and look similarly dense can differ
  // from "solves instantly" to "never solves" purely by luck of which
  // letter-position constraints they demand). A single shared deadline let
  // whichever template got tried *first* silently burn the entire budget
  // on a hard/unsolvable-for-this-corpus case, starving every other
  // template — including easy ones — of any chance to even be attempted.
  const perTemplateBudget = Math.max(50, Math.floor(timeBudget / templates.length));

  for (const rows of templates) {
    if (Date.now() > overallDeadline) break;
    const slots = extractSlots(rows);
    const longIds = computeLongSlotIds(slots);
    const domains = pruneDomains(slots, index);
    // Arc consistency can prove a template unsolvable for this exact word
    // pool outright (some slot's domain pruned to nothing) — skip straight
    // to the next template instead of burning its time slice on
    // backtracking search that's guaranteed to fail.
    if (slots.some((s) => (domains.get(s.id) || []).length === 0)) continue;
    const templateDeadline = Math.min(overallDeadline, Date.now() + perTemplateBudget);
    const { success, assignment } = runMaintainingArcConsistencyFill(slots, domains, longIds, templateDeadline, profile.targetDiff);
    if (success) {
      const grid = buildOutputFromSlots(rows, slots, assignment, n);
      if (openCellRatio(grid) >= minimumDensity) return grid;
    }
  }

  // Fallback chain: no template filled completely within budget (e.g. a
  // very narrow/thin word bank for this size+difficulty). Fall back to the
  // legacy greedy algorithm rather than fail puzzle creation outright.
  const legacy = legacyGenerate(wordBank, keywords, size, difficulty);
  if (legacy.words.length >= 3 && openCellRatio(legacy) >= minimumDensity) return legacy;

  throw new Error("could not meet the crossword density target for this combination — try again");
}

// =======================================================================
// Legacy greedy algorithm — kept as the last-resort fallback for when the
// template+backtracking approach above can't fully fill any template
// within its CPU budget (e.g. an extremely thin word bank). This is the
// original implementation, functionally unchanged.
// =======================================================================

const LEGACY_TARGET_WORDS = { mini: 10, quick: 16, compact: 30, standard: 42, large: 72 };
// Full grids are the most sensitive to a weak initial anchor. More restarts
// make the legacy safety net dependable without changing its dimensions or
// relaxing the existing density threshold.
const LEGACY_FILL_ATTEMPTS = 12;
const LEGACY_FILL_PASSES = 4;

function legacyGenerate(wordBank, keywords, size, difficulty) {
  const n = SIZE_MAP[size] || SIZE_MAP.standard;
  const maxDiff = (DIFFICULTY_PROFILES[difficulty] || DIFFICULTY_PROFILES.medium).maxDiff;
  const targetWords = LEGACY_TARGET_WORDS[size] || LEGACY_TARGET_WORDS.standard;

  const groups = legacyBuildCandidateGroups(wordBank, keywords, maxDiff, n);
  let result = legacyAttemptBest(groups, n, targetWords);

  if (result.words.length < 3 && keywords.length > 0) {
    const fallbackGroups = legacyBuildCandidateGroups(wordBank, [], maxDiff, n);
    result = legacyAttemptBest(fallbackGroups, n, targetWords);
  }

  if (result.words.length < 3) {
    return { words: [] };
  }

  return legacyCropAndNumber(result.grid, result.words, n);
}

function legacyAttemptBest(groups, n, targetWords) {
  let best = null;
  let bestScore = -1;
  for (let i = 0; i < LEGACY_FILL_ATTEMPTS; i++) {
    const candidates = groups.flatMap((g) => legacyShuffleByLength(g));
    const result = legacyAttemptFill(candidates, n, targetWords);
    const score = legacyDensityScore(result.grid, n);
    if (score > bestScore) {
      bestScore = score;
      best = result;
    }
  }
  return best;
}

function legacyDensityScore(grid, n) {
  let minRow = n, maxRow = -1, minCol = n, maxCol = -1, filled = 0;
  for (let r = 0; r < n; r++) {
    for (let c = 0; c < n; c++) {
      if (grid[r][c].letter) {
        minRow = Math.min(minRow, r);
        maxRow = Math.max(maxRow, r);
        minCol = Math.min(minCol, c);
        maxCol = Math.max(maxCol, c);
        filled++;
      }
    }
  }
  if (filled === 0) return 0;
  const area = (maxRow - minRow + 1) * (maxCol - minCol + 1);
  return filled * (filled / area);
}

function legacyBuildCandidateGroups(wordBank, keywords, maxDiff, n) {
  const seen = new Set();
  const deduped = [];
  for (const entry of wordBank) {
    const w = entry.w.toUpperCase();
    if (!/^[A-Z]+$/.test(w)) continue;
    if (w.length < 3 || w.length > n) continue;
    if (entry.diff > maxDiff) continue;
    if (seen.has(w)) continue;
    seen.add(w);
    deduped.push({ word: w, clue: entry.c, cat: entry.cat });
  }

  const STOPWORDS_LOCAL = new Set(["the", "and", "for", "with", "from", "that", "this", "are", "was", "were"]);
  const rawTokens = keywords
    .flatMap((k) => k.toLowerCase().split(/\s+/))
    .filter((t) => t.length >= 3 && !STOPWORDS_LOCAL.has(t));
  const keywordTokens = [...new Set(rawTokens.flatMap((t) => (t.endsWith("s") && t.length > 4 ? [t, t.slice(0, -1)] : [t])))];
  const matchCount = (entry) => {
    if (keywordTokens.length === 0) return 0;
    const hay = `${entry.word.toLowerCase()} ${entry.clue.toLowerCase()} ${entry.cat.toLowerCase()}`;
    return keywordTokens.reduce((n, t) => n + (hay.includes(t) ? 1 : 0), 0);
  };

  if (keywordTokens.length === 0) return [deduped];

  const strong = [];
  const weak = [];
  const general = [];
  for (const entry of deduped) {
    const n2 = matchCount(entry);
    if (n2 >= 2) strong.push(entry);
    else if (n2 === 1) weak.push(entry);
    else general.push(entry);
  }
  // Preserve theme priority while still allowing ordinary crossword fill to
  // complete a sparse large grid. Omitting the final group could leave a
  // themed fallback below its density floor even with thousands of usable
  // crossers available in the corpus.
  return [strong, weak, general];
}

function legacyShuffleByLength(list) {
  const byLength = new Map();
  for (const entry of list) {
    if (!byLength.has(entry.word.length)) byLength.set(entry.word.length, []);
    byLength.get(entry.word.length).push(entry);
  }
  const lengths = [...byLength.keys()].sort((a, b) => b - a);
  const out = [];
  for (const len of lengths) {
    const bucket = byLength.get(len);
    for (let i = bucket.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [bucket[i], bucket[j]] = [bucket[j], bucket[i]];
    }
    out.push(...bucket);
  }
  return out;
}

function legacyAttemptFill(candidates, n, targetWords) {
  if (candidates.length === 0) return { grid: legacyMakeEmptyGrid(n), words: [] };

  const grid = legacyMakeEmptyGrid(n);
  const words = [];
  const placedSet = new Set();

  const first = candidates[0];
  const startRow = Math.floor(n / 2);
  const startCol = Math.floor((n - first.word.length) / 2);
  legacyPlaceWord(grid, first.word, startRow, startCol, "across");
  words.push(legacyMakeWordRecord(first, startRow, startCol, "across", words.length));
  placedSet.add(first.word);

  for (let pass = 0; pass < LEGACY_FILL_PASSES && words.length < targetWords; pass++) {
    let placedThisPass = false;
    for (let idx = 1; idx < candidates.length && words.length < targetWords; idx++) {
      const entry = candidates[idx];
      if (placedSet.has(entry.word)) continue;
      const placement = legacyFindPlacement(grid, entry.word, n);
      if (!placement) continue;
      legacyPlaceWord(grid, entry.word, placement.row, placement.col, placement.direction);
      words.push(legacyMakeWordRecord(entry, placement.row, placement.col, placement.direction, words.length));
      placedSet.add(entry.word);
      placedThisPass = true;
    }
    if (!placedThisPass) break;
  }

  return { grid, words };
}

function legacyMakeWordRecord(entry, row, col, direction, tempId) {
  return { id: tempId, answer: entry.word, clue: entry.clue, row, col, direction, length: entry.word.length };
}

function legacyMakeEmptyGrid(n) {
  const grid = [];
  for (let r = 0; r < n; r++) {
    const row = [];
    for (let c = 0; c < n; c++) row.push({ letter: null, across: false, down: false });
    grid.push(row);
  }
  return grid;
}

function legacyInBounds(n, r, c) {
  return r >= 0 && r < n && c >= 0 && c < n;
}

function legacyFindPlacement(grid, word, n) {
  let fallback = null;
  for (let i = 0; i < word.length; i++) {
    const letter = word[i];
    for (let r = 0; r < n; r++) {
      for (let c = 0; c < n; c++) {
        const cell = grid[r][c];
        if (cell.letter !== letter) continue;

        let direction = null;
        if (cell.across && !cell.down) direction = "down";
        else if (cell.down && !cell.across) direction = "across";
        else continue;

        const row = direction === "down" ? r - i : r;
        const col = direction === "across" ? c - i : c;
        const overlaps = legacyValidPlacementOverlaps(grid, word, row, col, direction, n);
        if (overlaps === 0) continue;
        if (overlaps >= 2) return { row, col, direction };
        if (!fallback) fallback = { row, col, direction };
      }
    }
  }
  return fallback;
}

function legacyValidPlacementOverlaps(grid, word, row, col, direction, n) {
  return legacyIsValidPlacement(grid, word, row, col, direction, n) ? legacyCountOverlaps(grid, word, row, col, direction) : 0;
}

function legacyCountOverlaps(grid, word, row, col, direction) {
  const dRow = direction === "down" ? 1 : 0;
  const dCol = direction === "across" ? 1 : 0;
  let overlaps = 0;
  for (let i = 0; i < word.length; i++) {
    if (grid[row + dRow * i][col + dCol * i].letter) overlaps++;
  }
  return overlaps;
}

function legacyIsValidPlacement(grid, word, row, col, direction, n) {
  const dRow = direction === "down" ? 1 : 0;
  const dCol = direction === "across" ? 1 : 0;

  const endRow = row + dRow * (word.length - 1);
  const endCol = col + dCol * (word.length - 1);
  if (!legacyInBounds(n, row, col) || !legacyInBounds(n, endRow, endCol)) return false;

  const beforeRow = row - dRow;
  const beforeCol = col - dCol;
  if (legacyInBounds(n, beforeRow, beforeCol) && grid[beforeRow][beforeCol].letter) return false;
  const afterRow = row + dRow * word.length;
  const afterCol = col + dCol * word.length;
  if (legacyInBounds(n, afterRow, afterCol) && grid[afterRow][afterCol].letter) return false;

  let hasIntersection = false;
  for (let i = 0; i < word.length; i++) {
    const r = row + dRow * i;
    const c = col + dCol * i;
    const cell = grid[r][c];

    if (cell.letter) {
      if (cell.letter !== word[i]) return false;
      if (direction === "across" && cell.across) return false;
      if (direction === "down" && cell.down) return false;
      hasIntersection = true;
      continue;
    }

    const perp1r = r + dCol;
    const perp1c = c + dRow;
    const perp2r = r - dCol;
    const perp2c = c - dRow;
    if (legacyInBounds(n, perp1r, perp1c) && grid[perp1r][perp1c].letter) return false;
    if (legacyInBounds(n, perp2r, perp2c) && grid[perp2r][perp2c].letter) return false;
  }

  return hasIntersection;
}

function legacyPlaceWord(grid, word, row, col, direction) {
  const dRow = direction === "down" ? 1 : 0;
  const dCol = direction === "across" ? 1 : 0;
  for (let i = 0; i < word.length; i++) {
    const r = row + dRow * i;
    const c = col + dCol * i;
    grid[r][c].letter = word[i];
    if (direction === "across") grid[r][c].across = true;
    else grid[r][c].down = true;
  }
}

function legacyCropAndNumber(grid, words, n) {
  // Preserve the selected dimensions even when the dense-template solver
  // falls back to the greedy fill. Cropping made Quick and Compact appear
  // indistinguishable from neighboring sizes and contradicted the preview.
  const minRow = 0, minCol = 0;
  const rows = n, cols = n;

  const cells = [];
  const numberAt = new Map();
  let nextNumber = 1;

  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      const src = grid[r + minRow][c + minCol];
      const block = !src.letter;
      let number = null;
      if (!block) {
        const startsAcross = src.across && (c === 0 || !grid[r + minRow][c + minCol - 1].letter) && c + 1 < cols && grid[r + minRow][c + minCol + 1]?.letter;
        const startsDown = src.down && (r === 0 || !grid[r + minRow - 1][c + minCol]?.letter) && r + 1 < rows && grid[r + minRow + 1]?.[c + minCol]?.letter;
        if (startsAcross || startsDown) {
          number = nextNumber++;
          numberAt.set(`${r}-${c}`, number);
        }
      }
      cells.push({ row: r, col: c, letter: block ? null : src.letter, block, number });
    }
  }

  const finalWords = words
    .map((w) => {
      const row = w.row - minRow;
      const col = w.col - minCol;
      const number = numberAt.get(`${row}-${col}`) || null;
      const wordCells = [];
      for (let i = 0; i < w.length; i++) {
        wordCells.push(w.direction === "across" ? [row, col + i] : [row + i, col]);
      }
      return { number, direction: w.direction, answer: w.answer, clue: w.clue, row, col, length: w.length, cells: wordCells };
    })
    .filter((w) => w.number !== null)
    .sort((a, b) => a.number - b.number || (a.direction === "across" ? 0 : 1) - (b.direction === "across" ? 0 : 1));

  return { rows, cols, cells, words: finalWords };
}
